name: QuestWorld
version: ${version}
author: mrCookieSlime
authors: [ezeiger92, erik1988]
website: https://github.com/ezeiger92/QuestWorld2
api-version: 1.16

main: com.questworld.QuestWorldPlugin
softdepend: [ASkyBlock, ChatReaction, Citizens, PlaceholderAPI, Vault, Votifier, Bullion]

commands:
  quests:
    description: Opens up your quest book
    usage: /quests [category id [quest id]]
    permission: QuestWorld.quests
  betaquests:
    description: Opens up your quest book
    usage: /quests [category id [quest id]]
    permission: QuestWorld.quests
  questeditor:
    description: Opens up the quest editor
    usage: /questeditor <gui/import/export>
    aliases: [qe]
    permission: QuestWorld.editor
  q-external:
    description: Command progress for external command missions
    usage: /q-external <player> <id> [amount]
    permission: QuestWorld.editor

permissions:
  QuestWorld.editor:
    description: Allows you to use /questeditor
    default: op
  QuestWorld.quests:
    description: Allows you to use /quests
    default: true
